# Check if html websites changed since the last time this action was run
name: 'Check website changed' 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check change and commit a new sha to repo
        id: checkchange
        run: |
          URL=${{ secrets.URL }}
          curl $URL | sha1sum > sha_sum

          git config --global user.email "gha@test.com"
          git config --global user.name "GHA"
          git add sha_sum
          git commit -m "website $URL has changed since last time"  # This line will fail if the sha of the website does not change - Action will not push in that case
          git push
          
