# Check if html websites changed since the last time this action was run
name: 'Check website changed' 
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check change and commit a new sha to repo
        uses: actions/setup-python@v2
        id: checkchange
        run: |
          URL=${{ secrets.URL }}
          pip install requests
          python3 make_request.py $URL

          git config --global user.email "gha@test.com"
          git config --global user.name "GHA"
          git add sha_sum
          dt=$(date)
          
          (git diff --staged --quiet --exit-code); if [[ "$?" -eq "1" ]]; then git commit -m "$dt"; else echo "No changes to SHA"; fi
          git push
